#!/usr/bin/env bash
# Bash script that displays Best School 10 times.
i=0

while [ $i -lt 10 ]
do
    echo "Best School"
    ((i++))
    if [ $i = 4 ]
    then
        echo "bad luck"
    elif [ $i = 8 ]
    then
        echo "good luck"
    fi
done
