#!/usr/bin/env bash
# Bash script that displays Best School 10 times.
i=0

while [ $i -lt 8 ]
do
    echo "Best School"
    ((i++))
    if [ $i = 3 ]
    then
        echo "bad luck"
    elif [ $i = 7 ]
    then
        echo "good luck"
    else
    fi
done
