#!/usr/bin/env bash
# Bash script that displays Best School 20 times.
i=0

while [ $i -lt 20 ]
do
    ((i++))
    if [ $i = 4 ]
    then
        echo "bad luck from China"
    elif [ $i = 9 ]
    then
        echo "bad luck from Japan"
    elif [ $i = 17 ]
    then
        echo "bad luck from Italy"
    else
        echo "Best School"
    fi
done
